# docker/docker-compose.yml
# ------------------------------------------------------------
# Docker Compose to orchestrate FastAPI API and Streamlit UI
# for the Fraud Detection demo project
# ------------------------------------------------------------

version: "3.8"

services:
  api:
    container_name: fraud-api
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./models:/app/models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  streamlit:
    container_name: fraud-streamlit
    build:
      context: ./docker/streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

# ------------------------------------------------------------
# Example commands:
# Build and start both services:
#   docker-compose -f docker/docker-compose.yml up --build
#
# Run in detached mode:
#   docker-compose -f docker/docker-compose.yml up -d --build
#
# Stop services:
#   docker-compose -f docker/docker-compose.yml down
# ------------------------------------------------------------
